### ISSUE TITLE
Creating a context from kubeconfig results to an altered kubernetes endpoint

### ISSUE THREAD

**Issue by alexmavr** [docker/cli#1837]
**Description**

I'm trying to run the CLI from within a GKE kubernetes cluster, with a command similar to the following:

```
docker context create --docker from-current=true --kubernetes config-file=/path/to/kubeconfig --default-stack-orchestrator=kubernetes mycontext
```

In the `kubeconfig` file, there is a single `cluster` entry, with the `server` field that maps to an externally-routable IP address.

After the context is created, `docker context ls` shows a different IP address, which routes to the Kubernetes API server internally.

This behavior prevents me from using `docker context export` and `docker context import` among different clients. 

**Steps to reproduce the issue:**
1. Create a kubernetes cluster on GKE
2. Create a kubeconfig with the GKE cluster's external IP address
3. Create a context from the kubeconfig file
4. Use `docker context ls` to verify that the Kubernetes IP address is different than the one specified in the `kubeconfig`

**Output of `docker version`:**

```
Client:
 Version:           19.03.0-dev
 API version:       1.40
 Go version:        go1.12.1
 Git commit:        39f30ef1
 Built:             Wed Apr  3 18:05:33 2019
 OS/Arch:           linux/amd64
 Experimental:      false
```
cc @simonferquel @chris-crone

**Comment by simonferquel** [comment]
I can't reproduce with running context create locally (I can successfully setup my context to target the gke cluster).
I suppose you create the context from within a POD ?

**Comment by simonferquel** [comment]
Just did the same with a gcloud container + docker cli 19.03 beta1 within a POD, can't reproduce either.

**Comment by alexmavr** [comment]
I just reproduced this on v19.03.0-beta3 on two different GKE clusters and it's still failing for me:

1) On a GKE cluster, run a pod with the `v19.03.0-beta3` CLI binary
2) `kubectl exec -it <pod> sh` into the pod
3) Create a kubeconfig file such as the following:
```
apiVersion: v1
kind: Config
users:
- name: armada
  user:
    token: <base64-token>
clusters:
- cluster:
    certificate-authority-data: <ca data>
    server: https://35.226.**.**:443
  name: test-cluster
contexts:
- context:
    cluster: test-cluster
    user: armada
  name: test-cluster-armada
```
4) Create the context
```
docker context create --docker host=unix:///var/run/docker.sock --kubernetes config-file=/path/to/kubeconfig test-cluster-1
```

5) View the context and witness a different IP
```
$ docker context ls
NAME                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT                ORCHESTRATOR
default *           Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                                      swarm
test-cluster-1                                                unix:///var/run/docker.sock   https://10.55.240.1:443 (armada) 
```
