### ISSUE TITLE
ARG in FROM causes invalid reference format

### ISSUE THREAD

**Issue by mschoettle** [docker/cli#2225]
**Description**

I am trying to declare an `ARG` before `FROM` for the version of the base image to then use it in the `FROM` statement, as explained here: https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

However, building fails as described below.

**Steps to reproduce the issue:**
1. Create `Dockerfile` with the following content:

```
ARG VERSION=3.10.3
FROM alpine:${VERSION} AS builder
```
2. Build

**Describe the results you received:**

I receive the following error:

```
Sending build context to Docker daemon 

error during connect: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&target=&ulimits=null&version=1: invalid reference format
```

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.5
 API version:       1.40
 Go version:        go1.12.12
 Git commit:        633a0ea
 Built:             Wed Nov 13 07:37:22 2019
 OS/Arch:           linux/arm
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.5
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.12
  Git commit:       633a0ea
  Built:            Wed Nov 13 07:31:17 2019
  OS/Arch:          linux/arm
  Experimental:     false
 containerd:
  Version:          1.2.10
  GitCommit:        b34a5c8af56e510852c35414db4c1f4fa6172339
 runc:
  Version:          1.0.0-rc8+dev
  GitCommit:        3e425f80a8c931f88e6d94a8c831b9d5aa481657
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**

Raspian Buster (10) on RPI 4

**Comment by cpuguy83** [comment]
The referenced article is does not exist.

Have you tried this with `DOCKER_BUILDKIT=1`?

**Comment by mschoettle** [comment]
I corrected the URL to the referenced article.

I can confirm that it works with `DOCKER_BUILDKIT=1`.

**Comment by cpuguy83** [comment]
Ok so it seems like the docs just need to be updated. I don't think the old (non-buildkit) builder will be updated to support this.

**Comment by thaJeztah** [comment]
I'm not able to reproduce this issue (both with and without buildkit enabled);

```console
DOCKER_BUILDKIT=0 docker build .
Sending build context to Docker daemon  2.048kB
Step 1/2 : ARG VERSION=3.10.3
Step 2/2 : FROM alpine:${VERSION} AS builder
3.10.3: Pulling from library/alpine
Digest: sha256:c19173c5ada610a5989151111163d28a67368362762534d8a8121ce95cf2bd5a
Status: Downloaded newer image for alpine:3.10.3
 ---> 965ea09ff2eb
Successfully built 965ea09ff2eb
```

I'm not on an ARM machine though


Debug logs from the daemon show the same request as in this issue's description;

```
DEBU[2019-12-11T10:42:23.990644690Z] Calling HEAD /_ping
DEBU[2019-12-11T10:42:23.992062964Z] Calling POST /v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&target=&ulimits=null&version=1
DEBU[2019-12-11T10:42:24.059114139Z] Trying to pull alpine from https://registry-1.docker.io v2
DEBU[2019-12-11T10:42:25.450129948Z] Pulling ref from V2 registry: alpine:3.10.3
DEBU[2019-12-11T10:42:25.450232718Z] docker.io/library/alpine:3.10.3 resolved to a manifestList object with 7 entries; looking for a unknown/amd64 match
DEBU[2019-12-11T10:42:25.450247664Z] found match for linux/amd64 with media type application/vnd.docker.distribution.manifest.v2+json, digest sha256:e4355b66995c96b4b468159fc5c7e3540fcef961189ca13fee877798649f531a
DEBU[2019-12-11T10:42:25.882954678Z] pulling blob "sha256:89d9c30c1d48bac627e5c6cb0d1ed1eec28e7dbdfbcc04712e4c79c0f83faf17"
DEBU[2019-12-11T10:42:26.947525658Z] Downloaded 89d9c30c1d48 to tempfile /var/lib/docker/tmp/GetImageBlob075452187
DEBU[2019-12-11T10:42:26.949154927Z] Applying tar in /var/lib/docker/overlay2/43c6bc6890e20203489f7330af29c8f9cec5601d4e4d80ddbb6cb80ce6e811a8/diff  storage-driver=overlay2
DEBU[2019-12-11T10:42:27.099406590Z] Applied tar sha256:77cae8ab23bf486355d1b3191259705374f4a11d483b24964d2f729dd8c076a0 to 43c6bc6890e20203489f7330af29c8f9cec5601d4e4d80ddbb6cb80ce6e811a8, size: 5552690
DEBU[2019-12-11T10:42:33.351153763Z] Calling HEAD /_ping
DEBU[2019-12-11T10:42:33.352352560Z] Calling GET /v1.40/version
```


Although the error message you posted looks a bit odd, showing `http://` before `/var/run/docker.sock` ?

If I try to use an _invalid_ Dockerfile, I do get the "invalid reference format" error, but _don't_ see the `error during connect`;


```Dockerfile
#ARG VERSION=3.10.3
FROM alpine:${VERSION} AS builder
```

```console
docker build .
Sending build context to Docker daemon  2.048kB
Step 1/1 : FROM alpine:${VERSION} AS builder
invalid reference format
```

**Comment by mschoettle** [comment]
I enabled debug mode and ran `DOCKER_BUILDKIT=0 docker build .`. Here is the relevant part of the debug log:

```
level=info msg="API listen on /var/run/docker.sock"
level=debug msg="Calling HEAD /_ping"
level=debug msg="Calling POST /v1.40/build?buildargs=%7B%7D&cachefrom=%5B%5D&cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&labels=%7B%7D&memory=0&memswap=0&networkmode=default&rm=1&shmsize=0&target=&ulimits=null&version=1"
level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unexpected EOF" error_type="*errors.errorString" module=api
level=error msg="Handler for POST /v1.40/build returned error: unexpected EOF"
level=debug msg="FIXME: Got an API for which error does not match any expected type!!!: unexpected EOF" error_type="*errors.errorString" module=api
```

**Comment by thaJeztah** [comment]
> `unexpected EOF`

Looks like a different error than the original issue; is that with the same Dockerfile? Can you also post the output of `docker info`?

**Comment by mschoettle** [comment]
Yes, same Dockerfile with the same output/error on the console as in the issue description.

Output of `docker info`:

```
Client:
 Debug Mode: false

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 26
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.86-v7l+
 Operating System: Raspbian GNU/Linux 10 (buster)
 OSType: linux
 Architecture: armv7l
 CPUs: 4
 Total Memory: 3.814GiB
 Name: rpi
 ID: YHQC:JOSP:XPOB:D2CW:JIKK:3A4P:T2X4:3DP5:T7GA:CSRU:5JI4:2JDR
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 21
  Goroutines: 34
  System Time: 2019-12-11T11:12:13.502240614-05:00
  EventsListeners: 0
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
```

**Comment by thaJeztah** [comment]
There's an existing (but very old) issue where the error returned didn't provide information about the reasons _why_ (see https://github.com/moby/moby/issues/5270), but that was resolved in https://github.com/moby/moby/pull/5782.

Does the machine have enough disk space to (temporarily) store the uploaded build-context? It's also worth checking if there's any potential configuration issues. You can check that with this script; https://github.com/moby/moby/blob/master/contrib/check-config.sh (would have to be run on the machine where the daemon is running)

**Comment by mschoettle** [comment]
> Does the machine have enough disk space to (temporarily) store the uploaded build-context? 

Yes

> It's also worth checking if there's any potential configuration issues. You can check that with this script; 

Here's the output:

```
Generally Necessary:
- cgroup hierarchy: properly mounted [/sys/fs/cgroup]
- CONFIG_NAMESPACES: enabled
- CONFIG_NET_NS: enabled
- CONFIG_PID_NS: enabled
- CONFIG_IPC_NS: enabled
- CONFIG_UTS_NS: enabled
- CONFIG_CGROUPS: enabled
- CONFIG_CGROUP_CPUACCT: enabled
- CONFIG_CGROUP_DEVICE: enabled
- CONFIG_CGROUP_FREEZER: enabled
- CONFIG_CGROUP_SCHED: enabled
- CONFIG_CPUSETS: enabled
- CONFIG_MEMCG: enabled
- CONFIG_KEYS: enabled
- CONFIG_VETH: enabled (as module)
- CONFIG_BRIDGE: enabled (as module)
- CONFIG_BRIDGE_NETFILTER: enabled (as module)
- CONFIG_NF_NAT_IPV4: enabled (as module)
- CONFIG_IP_NF_FILTER: enabled (as module)
- CONFIG_IP_NF_TARGET_MASQUERADE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_ADDRTYPE: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_CONNTRACK: enabled (as module)
- CONFIG_NETFILTER_XT_MATCH_IPVS: enabled (as module)
- CONFIG_IP_NF_NAT: enabled (as module)
- CONFIG_NF_NAT: enabled (as module)
- CONFIG_NF_NAT_NEEDED: enabled
- CONFIG_POSIX_MQUEUE: enabled

Optional Features:
- CONFIG_USER_NS: enabled
- CONFIG_SECCOMP: enabled
- CONFIG_CGROUP_PIDS: enabled
- CONFIG_MEMCG_SWAP: missing
- CONFIG_MEMCG_SWAP_ENABLED: missing
- CONFIG_BLK_CGROUP: enabled
- CONFIG_BLK_DEV_THROTTLING: enabled
- CONFIG_IOSCHED_CFQ: enabled
- CONFIG_CFQ_GROUP_IOSCHED: enabled
- CONFIG_CGROUP_PERF: missing
- CONFIG_CGROUP_HUGETLB: missing
- CONFIG_NET_CLS_CGROUP: enabled (as module)
- CONFIG_CGROUP_NET_PRIO: missing
- CONFIG_CFS_BANDWIDTH: missing
- CONFIG_FAIR_GROUP_SCHED: enabled
- CONFIG_RT_GROUP_SCHED: missing
- CONFIG_IP_NF_TARGET_REDIRECT: enabled (as module)
- CONFIG_IP_VS: enabled (as module)
- CONFIG_IP_VS_NFCT: enabled
- CONFIG_IP_VS_PROTO_TCP: enabled
- CONFIG_IP_VS_PROTO_UDP: enabled
- CONFIG_IP_VS_RR: enabled (as module)
- CONFIG_EXT4_FS: enabled
- CONFIG_EXT4_FS_POSIX_ACL: enabled
- CONFIG_EXT4_FS_SECURITY: enabled
- Network Drivers:
  - "overlay":
    - CONFIG_VXLAN: enabled (as module)
    - CONFIG_BRIDGE_VLAN_FILTERING: missing
      Optional (for encrypted networks):
      - CONFIG_CRYPTO: enabled
      - CONFIG_CRYPTO_AEAD: enabled (as module)
      - CONFIG_CRYPTO_GCM: enabled (as module)
      - CONFIG_CRYPTO_SEQIV: enabled (as module)
      - CONFIG_CRYPTO_GHASH: enabled (as module)
      - CONFIG_XFRM: enabled
      - CONFIG_XFRM_USER: enabled
      - CONFIG_XFRM_ALGO: enabled
      - CONFIG_INET_ESP: enabled (as module)
      - CONFIG_INET_XFRM_MODE_TRANSPORT: enabled (as module)
  - "ipvlan":
    - CONFIG_IPVLAN: enabled (as module)
  - "macvlan":
    - CONFIG_MACVLAN: enabled (as module)
    - CONFIG_DUMMY: enabled (as module)
  - "ftp,tftp client in container":
    - CONFIG_NF_NAT_FTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_FTP: enabled (as module)
    - CONFIG_NF_NAT_TFTP: enabled (as module)
    - CONFIG_NF_CONNTRACK_TFTP: enabled (as module)
- Storage Drivers:
  - "aufs":
    - CONFIG_AUFS_FS: missing
  - "btrfs":
    - CONFIG_BTRFS_FS: enabled (as module)
    - CONFIG_BTRFS_FS_POSIX_ACL: enabled
  - "devicemapper":
    - CONFIG_BLK_DEV_DM: enabled (as module)
    - CONFIG_DM_THIN_PROVISIONING: enabled (as module)
  - "overlay":
    - CONFIG_OVERLAY_FS: enabled (as module)
  - "zfs":
    - /dev/zfs: missing
    - zfs command: missing
    - zpool command: missing

Limits:
- /proc/sys/kernel/keys/root_maxkeys: 1000000

```
