### ISSUE TITLE
[proposal] Add stack name to environment / allow substitution in compose file

### ISSUE THREAD

**Issue by nrueckmann** [docker/cli#2255]
I expect most naming conventions do leverage the name of the stack. Unfortunately, this name is not available for substitution in compose file. Since the stack name is known for any stack command, i propose to add the name of the stack as environment variable which can be used for substitution.

Example / Use case:
```
version: "3.7"
networks:
  default:
    external: true
    name: ${STACK_NAME}_default
```
Side note: Rancher does provide a similar feature already (see https://github.com/rancher/rancher/issues/3393).
