### ISSUE TITLE
Inconsistency in docker-compose file parsing?

### ISSUE THREAD

**Issue by lauxley** [docker/cli#3051]
Trying to use [gpu support](https://docs.docker.com/compose/gpu-support/#enabling-gpu-access-to-service-containers) in swarm mode.
When using the given compose file example in swarm mode, (with or without added placement constraint):

```yml
version: '3.9'
services:
  test:
    image: nvidia/cuda:10.2-base
    command: nvidia-smi
    deploy:
      mode: replicated
      placement:
        constraints:
        - node.hostname == gpu0
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu, utility]
```

```
$ docker --version
Docker version 20.10.3, build 48d30b5

$ docker stack deploy --compose-file docker-compose.test.yml gputest
services.test.deploy.resources.reservations Additional property devices is not allowed
```

The file parses correctly when doing
`$ docker-compose -f docker-compose.test.yml up`
