### ISSUE TITLE
Relative to the compose volume is mapped incorrectly in docker compose

### ISSUE THREAD

**Issue by Vadimkin** [docker/cli#3097]
**Description**

**Steps to reproduce the issue:**
1. Create `docker-compose.yml` with next content
```
version: '3.8'
services:
    reverse:
        hostname: reverse
        image: openresty/openresty:alpine
        ports:
            - "443:443"
        volumes:
            - ./docker/nginx/conf:/etc/nginx/conf.d
```
2. `docker-compose up`:

**Describe the results you received:**
```
Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /Users/vadimklimenko/Projects/temp/docker/nginx/conf
```

**Describe the results you expected:**

Container is started without any errors

**Additional information you deem important (e.g. issue happens only occasionally):**

```
→ docker-compose config
services:
  reverse:
    hostname: reverse
    image: openresty/openresty:alpine
    ports:
    - published: 443
      target: 443
    volumes:
    - /Users/vadimklimenko/Projects/temp/docker/nginx/conf:/etc/nginx/conf.d:rw
version: '3.8'
```

```
→ docker compose config
services:
  reverse:
    hostname: reverse
    image: openresty/openresty:alpine
    networks:
      default: null
    ports:
    - mode: ingress
      target: 443
      published: 443
      protocol: tcp
    volumes:
    - type: bind
      source: /Users/vadimklimenko/Projects/temp/docker/nginx/conf
      target: /etc/nginx/conf.d
networks:
  default:
    name: temp_default
```

This compose file is valid for `docker-compose`, but not for `docker compose`.
[By documentation](https://docs.docker.com/compose/compose-file/compose-file-v3/#volumes), this notation is supported:
```
  # Path on the host, relative to the Compose file
  - ./cache:/tmp/cache
```

**Output of `docker-compose version`:**

```
docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
➜  temp docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 88
  Running: 0
  Paused: 0
  Stopped: 88
 Images: 45
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 9.733GiB
 Name: docker-desktop
 ID: O7PI:WETW:DNF3:724N:4YOH:UN4Y:P5HX:KX27:NRMJ:T2GD:ASAG:EUPV
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 46
  Goroutines: 53
  System Time: 2021-05-14T08:45:35.7579229Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
