### ISSUE TITLE
Support for raw config in docker-compose file

### ISSUE THREAD

**Issue by WTFKr0** [docker/cli#320]
Hi

I can't find a way to add a raw config in docker-compose file, so I think it's not possible
What I am trying to do is to deploy a stack with a config like :

```
version: "3.3"
services:
  caddy:
    image: caddy
    configs:
      - source: caddyfile
        target: /etc/Caddyfile
configs:
  caddyfile:
    raw: |
0.0.0.0
browse
log stdout
errors stdout
```

I think it impact the compose format itself

Cheers
