### ISSUE TITLE
Networking differences between `docker-compose` and `docker compose`?

### ISSUE THREAD

**Issue by jonnyarnold** [docker/cli#3233]
Hi there!

We're seeing an unusual problem with our Django application, hosted in a Docker container and "orchestrated" by `docker-compose`.

Our system is set up with a few containers:

```yaml
# docker-compose.yml, with parts truncated
version: "3.7"

services:
  web:
    # ...
    ports:
      - 8000:8000
    networks:
      - db_network
    depends_on:
      - db
    tty: true

  async:
    command: ./manage.py run_huey --flush-locks --workers 4
    stop_signal: SIGINT
    stop_grace_period: 60s
    environment:
      - DJANGO_SETTINGS_MODULE=nomio.settings.dev
    env_file:
      - web/secrets.env
    volumes:
      - ./web:/opt/web
    networks:
      - db_network
    depends_on:
      - db
    tty: true

  db:
    image: postgres:12.3
    # ...

networks:
  db_network:
    driver: bridge
```

Our `async` container polls an e-mail inbox at `imap.gmail.com:993` every minute. 

Running with `docker-compose up` this succeeds, but running with `docker compose up` fails with an authentication failure:

```
# via docker-compose up
async_1           | 2021-08-05 10:29:25 | INFO     | Executing importer.tasks.import_from_email.import_from_email: d5f16fc4-1902-401d-85e9-4cd294eace90
async_1           | 2021-08-05 10:29:28 | INFO     | nomio.importer.tasks.import_from_email.import_from_email.acknowledgements_sent(task_id='d5f16fc4-1902-401d-85e9-4cd294eace90', user_ids=set())
async_1           | 2021-08-05 10:29:28 | INFO     | importer.tasks.import_from_email.import_from_email: d5f16fc4-1902-401d-85e9-4cd294eace90 executed in 2.240s

# via docker compose up
async_1           | 2021-08-05 09:49:30 | INFO     | Executing importer.tasks.import_from_email.import_from_email: d9b75cac-cfa6-4a59-8c3e-a0709118b0fc
async_1           | 2021-08-05 09:49:31 | ERROR    | Unhandled exception in task d9b75cac-cfa6-4a59-8c3e-a0709118b0fc.
async_1           | Traceback (most recent call last):
async_1           |   File "/usr/local/lib/python3.9/site-packages/huey/api.py", line 367, in _execute
async_1           |     task_value = task.execute()
async_1           |   File "/usr/local/lib/python3.9/site-packages/huey/api.py", line 740, in execute
async_1           |     return func(*args, **kwargs)
async_1           |   File "/usr/local/lib/python3.9/site-packages/huey/contrib/djhuey/__init__.py", line 133, in inner
async_1           |     return fn(*args, **kwargs)
async_1           |   File "/usr/local/lib/python3.9/site-packages/huey/api.py", line 823, in inner
async_1           |     return fn(*args, **kwargs)
async_1           |   File "/opt/web/core/task_helpers.py", line 13, in wrapped_func
async_1           |     raise e
async_1           |   File "/opt/web/core/task_helpers.py", line 10, in wrapped_func
async_1           |     return func(*args, **kwargs)
async_1           |   File "/opt/web/core/logging.py", line 184, in with_log_context
async_1           |     return func(*args, **kwargs)
async_1           |   File "/opt/web/importer/tasks/import_from_email.py", line 169, in import_from_email
async_1           |     for attachment in client.new_import_attachments:
async_1           |   File "/opt/web/importer/tasks/import_from_email.py", line 82, in new_import_attachments
async_1           |     with self.inbox as mailbox:
async_1           |   File "/opt/web/importer/tasks/import_from_email.py", line 154, in inbox
async_1           |     return MailBox(self.url, port=self.port).login(
async_1           |   File "/usr/local/lib/python3.9/site-packages/imap_tools/mailbox.py", line 41, in login
async_1           |     login_result = self.box.login(username, password)
async_1           |   File "/usr/local/lib/python3.9/imaplib.py", line 612, in login
async_1           |     raise self.error(dat[-1])
async_1           | imaplib.IMAP4.error: b'[AUTHENTICATIONFAILED] Invalid credentials (Failure)'
```

Are there any networking differences between `docker-compose` and `docker compose` that I'm missing?

Thanks for your help in advance 🙂
