### ISSUE TITLE
Image Manifest Override 

### ISSUE THREAD

**Issue by EmbeddedAndroid** [docker/cli#327]
### Problem description

Using the image manifest schema I can describe multiple architecture images under a single namespace and tag. 

For my base images, I use tools like debootstrap, mkimage-alpine, etc to create compressed root file systems imported as docker layers. These tools allow the user to specify a target architecture, to allow the users to create ABI compatible root file systems on a single host.  As an example, arm64 targets are ABI compatible with armhf, I can also produce armhf tar balls on my arm64 host without issue.

After I've imported the root file systems, I then create a manifest to create a single multi arch image from these outputs.
 
```
image: linarotechnologies/alpine:3.6
manifests:
  -
    image: linarotechnologies/alpine:3.6-arm64
    platform:
      architecture: arm64
      os: linux
  -
    image: linarotechnologies/alpine:3.6-armhf
    platform:
      architecture: arm
      os: linux
  -
    image: alpine:3.6
    platform:
      architecture: amd64
      features:
        - sse
      os: linux
```

Everything works beautifully, on x86, arm64, or armhf hosts! However, the issue I'm facing now is when building container based on this multi-arch base images. Take for example the following Dockerfile statement:

```
FROM linarotechnologies/alpine:edge
```

When building this Dockerfile, the image which is pulled matches the docker host's architecture. What happens if a user wishes to build an ABI compatible image using another architecture? Some examples:

amd64 host wishes to build an i386 image
arm64 host wishes to build an  armhf image
mips64 host wishes to build an mips image

There may be more architectures with ABI compatibility but this gives you a basic idea of the problem.

### Project version(s) affected

Latest Docker Version (Tested with v1.13)

### Suggestions for a fix

I would suggest docker implements a simple --arch flag, which would force the specified architecture to be used when resolving the image from the manifest. 

```
docker build -t myimage --arch=armhf -f Dockerfile .
docker run -it --arch=armhf myimage
```
