### ISSUE TITLE
touchscreen not works in contenerized graphical app on raspberry pi 4

### ISSUE THREAD

**Issue by FilMar** [docker/cli#3292]
Hello,
i am trying to containerize a GUI app with flutter_pi in a raspberry pi 4.
I'm running the container in privileged mode, the graphics work but i can't get the touchscreen to work despite using evtest inside the container the touch is detected,
attached the dockerfile of the image:

```
FROM ubuntu

RUN apt -y update && apt -y install git && apt -y install wget 

WORKDIR /TOWER_DISPLAY

RUN git clone --depth 1 https://github.com/ardera/flutter-engine-binaries- for-arm.git engine-binaries && \ 
    cd engine-binaries && \
    ./install.sh

ENV TZ=Europe/Rome
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
RUN apt -y install cmake \
               libgl1-mesa-dev \
               libgles2-mesa-dev \
               libegl1-mesa-dev \
               libdrm-dev \
               libgbm-dev

RUN DEBIAN_FRONTEND='noninteractive' apt -y install ttf-mscorefonts-installer
RUN apt -y install fontconfig \
                libsystemd-dev \
                libinput-dev \
                libudev-dev \
                libxkbcommon-dev

#STEP 3 DIPENDENZE
RUN fc-cache

RUN git clone https://github.com/ardera/flutter-pi
WORKDIR /TOWER_DISPLAY/flutter-pi/build
RUN cmake ..
RUN make -j `nproc`
RUN make install

WORKDIR /TOWER_DISPLAY

COPY ./flutter_assets ./flutter_assets

CMD flutter-pi --release ./flutter_assets
```
the container is run by docker compose by adding the following compose-file:
```
    DisplayTower:
      image: emotionsrl/tower-display
      restart: always
      privileged: true
      depends_on:
        - "msgCenter"
        - "hwManager"
      volumes:
        - "data:/data"
```

Thank you in advance for your help.
