### ISSUE TITLE
Include an "order" key in the "update_config"

### ISSUE THREAD

**Issue by akalipetis** [docker/cli#346]
When updating a Docker service, the following option exists:

```bash
      --update-order string                Update order ("start-first"|"stop-first")
```

This can be used to create rolling update deployments, even if a service has just one replica.

I propose adding the following key to the Docker Compose spec, which will allow for these updates to work with `docker deploy -c ...`.

```yml
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        order: start-first | stop-first
```

I would be happy to contribute the needed code if that's something we'd like to have in the spec.
