### ISSUE TITLE
Option to specify network scope in compose file

### ISSUE THREAD

**Issue by manishtomar** [docker/cli#410]
One can create network with scope using `--scope` option in `docker network create` command. However, there is no corresponding option in compose file. The file can have `scope: local|swarm` as an option under `networks -> network name` section in the file. An example is
```yaml
networks:
  local:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
    scope: swarm
```

Please add this option in compose file and corresponding translation in CLI. Thanks!
