### ISSUE TITLE
Non consistent output of `docker ps -a` and `docker ps -all`

### ISSUE THREAD

**Issue by glaux** [docker/cli#520]
**Description**

The output of the commands `docker ps -a` and `docker ps -all` are not the same, see output below.

**Steps to reproduce the issue:**
Run the docker-compose file:

```yml
version: '3.3'

services:

  mysql:
    image: mysql/mysql-server:5.7
    env_file:
      - ./docker/drupal/environment/drupal.env
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql:/docker-entrypoint-initdb.d
    restart: always

  drupal:
    build: ./docker/drupal
    ports:
      - "8090:80"
    volumes:
      - /var/www/html/modules
      - /var/www/html/themes
      - /var/www/html/libraries
      - /var/www/html/profiles
      - /var/www/html/sites
    depends_on:
      - mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    env_file:
      - ./docker/drupal/environment/drupal.env
    ports:
      - "8080:80"
    depends_on:
      - mysql
    restart: always
```

Contents of the drupal dockerfile:

```dockerfile
FROM drupal:8.3.6-apache

# Copy Drupal extensions
COPY modules /var/www/html/modules/
COPY themes /var/www/html/themes/
COPY libraries /var/www/html/libraries/
COPY profiles /var/www/html/profiles/

# Copy sites and make the public files directory writeable
COPY sites /var/www/html/sites/
RUN chown -R www-data:www-data /var/www/html/sites/default/files

# Create the private files directory
RUN mkdir /var/private_files
RUN chown -R www-data:www-data /var/private_files

# Copy environment
RUN mkdir /var/keys
RUN mkdir /var/environment
COPY keys /var/keys/
COPY environment /var/environment/
```

**Describe the results you received:**

When running the various commands to list the containers I get the following:

```
$ docker ps -all
CONTAINER ID        IMAGE                          COMMAND                CREATED             STATUS                     PORTS               NAMES
3e6f7478b3fc        phpmyadmin/phpmyadmin:latest   "/run.sh phpmyadmin"   15 minutes ago      Exited (0) 9 minutes ago                       intervention_phpmyadmin_1

$ docker ps -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                     PORTS               NAMES
3e6f7478b3fc        phpmyadmin/phpmyadmin:latest   "/run.sh phpmyadmin"     15 minutes ago      Exited (0) 9 minutes ago                       intervention_phpmyadmin_1
694eb8271ac9        intervention_drupal            "docker-php-entryp..."   15 minutes ago      Exited (0) 9 minutes ago                       intervention_drupal_1
0bf4ebbaa557        mysql/mysql-server:5.7         "/entrypoint.sh my..."   15 minutes ago      Exited (0) 9 minutes ago                       intervention_mysql_1

$ docker container ls -a
CONTAINER ID        IMAGE                          COMMAND                  CREATED             STATUS                      PORTS               NAMES
3e6f7478b3fc        phpmyadmin/phpmyadmin:latest   "/run.sh phpmyadmin"     28 minutes ago      Exited (0) 22 minutes ago                       intervention_phpmyadmin_1
694eb8271ac9        intervention_drupal            "docker-php-entryp..."   28 minutes ago      Exited (0) 22 minutes ago                       intervention_drupal_1
0bf4ebbaa557        mysql/mysql-server:5.7         "/entrypoint.sh my..."   28 minutes ago      Exited (0) 22 minutes ago                       intervention_mysql_1

```

**Describe the results you expected:**
I expected all of the above commands to output the exact same thing.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:57:19 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:19 2017
 OS/Arch:      linux/amd64
 Experimental: true
```

**Output of `docker info`:**

```
$ docker info
Containers: 3
 Running: 0
 Paused: 0
 Stopped: 3
Images: 24
Server Version: 17.06.2-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 6e23458c129b551d5c9871e5174f6b1b7f6d1170
runc version: 810190ceaa507aa2727d7ae6f4790c76ec150bd2
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.41-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: 3XNU:2NFU:6U2R:V5Q5:4S3S:3RH5:4323:JAYX:HNL4:2K26:LRWD:UOI3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 15
 Goroutines: 26
 System Time: 2017-09-11T07:55:04.4119361Z
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Additional environment details (AWS, VirtualBox, physical, etc.):**
I'm running my setup on Windows 10 pro 64bit
