### ISSUE TITLE
Property name in volume, config and secret are not prefixed with stack name

### ISSUE THREAD

**Issue by pszczekutowicz** [docker/cli#811]
**Description**
When property name is defined in objects like volumes, configs and secrets and there is no external property set to true objects name created by docker stack deploy are created without stack name prefix.

Lets say we have  project with several stacks named by domain and each stack contains several service. Some of services names are repeating. For example stacks **shop** and stack **warehouse** both of them have services named **orders**. Both stacks are located in separated directories and are deployed to same cluster.

stack **shop**
```
version: "3.5"
services:
  orders:
    image: orders:v1
    configs:
      - source: orders
        target: /usr/src/app/config/local.json
    volumes:
      - orders_cache:/usr/src/app/cache:rw
configs:
  orders:
    name: orders_v1
    file: ./orders.json
volumes:
  orders_cache:
    name: orders_cache_v1
```
stack **warehouse**
```
version: "3.5"
services:
  orders:
    image: orders:v1
    configs:
      - source: orders
        target: /usr/src/app/config/local.json
    volumes:
      - orders_cache:/usr/src/app/cache:rw
configs:
  orders:
    name: orders_v1
    file: ./orders.json
volumes:
  orders_cache:
    name: orders_cache_v1
```
As you can see in docker >=17.12 when name property is used there will be issue with configuration files. There can be similar issue with secrets. Above example also shows conflict with volumes.

Regarding volumes. For example I can imagine one stack deployed twice in one cluster with different names, lets say development and testing. If I create volume for database with property name as there will be no stack name prefix there will be one volume for two environments.
